<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-18 at 19:25:43.
 */
class InflectsManagerTest extends PHPUnit_Framework_TestCase {

    /**
     * @covers InflectsManager::getInflections
     * @todo   Implement testGetInflections().
     */
    public function testGetInflections() {
        //$result = InflectsManager::inst()->getInflection('');
    }

    /**
     * @covers InflectsManager::getInflection
     * @todo   Implement testGetInflection().
     */
    public function testGetInflection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers InflectsManager::inst
     * @todo   Implement testInst().
     */
    public function testInst() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
