<?php

/**
 * Фолдинг 'Диалоговые окна' (dg)
 *
 * @author autogenerated
 */
final class DialogManager extends DialogResources implements PageFinalizerFolding {

    /** @return BaseDialog */
    public function getDialog($ident) {
        return $this->getEntityClassInst(get_file_name($ident));
    }

    public function finalizePageContent($CONTENT) {
        $links = array();
        /** @var $inst BaseDialog */
        foreach ($this->getAllUserAcessibleClassInsts() as $inst) {
            $links[] = $inst->getFoldedEntity()->getResourcesLinks();
        }
        return $CONTENT . implode('', $links);
    }

    /** @return DialogManager */
    public static function inst() {
        return parent::inst();
    }

}

?>