<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-17 at 17:55:26.
 */
class AutoloadDirTest extends BasePsTest {

    /**
     * @covers AutoloadDir::getClassPath
     */
    public function testGetClassPath() {
        $cpDir = new AutoloadDir(DirItem::inst(Autoload::DIR_TESTS));
        $searchedCp = $cpDir->getClassPath(ClassA::get__CLASS__());
        $searchedCp = str_replace('/', '\\', $searchedCp);

        $realCp = ClassA::get__FILE__();
        $realCp = str_replace('/', '\\', $realCp);

        self::log("Real CP: [$realCp]");
        self::log("Searched CP: [$searchedCp]");

        $this->assertEquals($searchedCp, $realCp);
    }

    /**
     * @covers AutoloadDir::isRebuilded
     */
    public function testIsRebuilded() {
        //Запросим путь к тестовому классу, чтобы он уже наверняка был найден на момент запроса.
        $this->assertNotNull(Autoload::inst()->getClassPath(ClassA::get__CLASS__()));

        //Мы должны найти нагш класс без перезагрузки, так как уже нашли его ранее
        $cpDir = new AutoloadDir(DirItem::inst(Autoload::DIR_TESTS));
        $this->assertNotNull($cpDir->getClassPath(ClassA::get__CLASS__()));
        $this->assertFalse($cpDir->isRebuilded());
    }

}
