<?php

/**
 * Базовый класс для всех сущностей фолдинга '{$EntityName}' ({$funique})
 *
 * @author autogenerated
 */
abstract class {$BaseClass} extends FoldedClass {

    protected function _construct() {
        //Конструируем объект
    }

}

?>