<?php

/**
 * Фолдинг '{$EntityName}' ({$funique})
 *
 * @author autogenerated
 */
final class {$ManagerClass} extends {$ResourcesClass} {

    /** @return {$BaseClass} */
    public function get{$FoldingClassPrefix}($ident) {
        return $this->getEntityClassInst(get_file_name($ident));
    }

    /** @return {$ManagerClass} */
    public static function inst() {
        return parent::inst();
    }

}

?>