<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-24 at 18:50:19.
 */
class PsShotdownTest extends BasePsTest {

    /**
     * @covers PsShotdown::registerDestructable
     */
    public function testCloseOrder() {
        $this->assertClassHasDifferentConstValues('PsShotdown');
    }

    /**
     * @covers PsShotdown::registerDestructable
     */
    public function testRegisterDestructable() {
        $Destructable = new TestDestructable();
        PsShotdown::registerDestructable($Destructable, PsShotdown::TestDestructable);
        try {
            PsShotdown::registerDestructable($Destructable, PsShotdown::TestDestructable);
            $this->brakeNoException();
        } catch (PException $ex) {
            
        }
    }

}